// @ts-nocheck
import { z } from "zod";
import { protectedProcedure, router } from "../_core/trpc";
import { TRPCError } from "@trpc/server";
import { getDb } from "../db";
import { clientAdvances, clientAdvanceDeductions, clients, financialEntries, cargoLoads, cargoWeeklyClosings } from "../../drizzle/schema";
import { eq, desc, and, asc, ne } from "drizzle-orm";
import { storagePut } from "../storage";

export const clientAdvancesRouter = router({
  // Listar adiantamentos de um cliente
  list: protectedProcedure
    .input(z.object({ clientId: z.number() }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      return db.select().from(clientAdvances)
        .where(eq(clientAdvances.clientId, input.clientId))
        .orderBy(desc(clientAdvances.date));
    }),

  // Listar adiantamentos de um cliente (alias para uso no CargoControl)
  listByClient: protectedProcedure
    .input(z.object({ clientId: z.number() }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      return db.select().from(clientAdvances)
        .where(eq(clientAdvances.clientId, input.clientId))
        .orderBy(desc(clientAdvances.date));
    }),

  // Listar todos os adiantamentos (para uso no PDF do CargoControl)
  listAll: protectedProcedure
    .query(async () => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      return db.select().from(clientAdvances)
        .orderBy(desc(clientAdvances.date));
    }),

  // Criar novo adiantamento
  create: protectedProcedure
    .input(z.object({
      clientId: z.number(),
      amount: z.number().positive(),
      description: z.string().optional(),
      receiptUrl: z.string().optional(),
      date: z.string(),
      startDate: z.string().optional(),  // data de início dos abatimentos
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      // Buscar nome do cliente
      const [client] = await db.select({ name: clients.name }).from(clients).where(eq(clients.id, input.clientId));
      const clientName = client?.name || `Cliente #${input.clientId}`;

      const [result] = await db.insert(clientAdvances).values({
        clientId: input.clientId,
        amount: String(input.amount),
        balanceRemaining: String(input.amount),
        description: input.description,
        receiptUrl: input.receiptUrl,
        date: input.date,
        startDate: input.startDate || null,
        status: 'ativo',
        createdBy: ctx.user.id,
      });
      const advanceId = (result as any).insertId;

      // Lançar automaticamente no financeiro como despesa
      try {
        const refMonth = input.date.slice(0, 7); // "2026-05"
        const desc = input.description
          ? `Adiantamento para ${clientName} - ${input.description}`
          : `Adiantamento para ${clientName}`;
        await db.insert(financialEntries).values({
          type: 'despesa',
          category: 'adiantamento_cliente',
          description: desc,
          amount: String(input.amount),
          date: input.date,
          referenceMonth: refMonth,
          paymentMethod: 'pix',
          status: 'confirmado',
          clientId: input.clientId,
          clientName,
          notes: `Adiantamento ID #${advanceId} registrado automaticamente`,
          registeredBy: ctx.user.id,
          registeredByName: ctx.user.name,
          autoGenerated: 1,
        });
      } catch (e) {
        // Não bloquear criação do adiantamento se o lançamento financeiro falhar
        console.error('[clientAdvances] Erro ao lançar no financeiro:', e);
      }

      return { id: advanceId };
    }),

  // Buscar saldo total de adiantamentos ativos de um cliente
  getBalance: protectedProcedure
    .input(z.object({ clientId: z.number() }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      const advances = await db.select().from(clientAdvances)
        .where(and(
          eq(clientAdvances.clientId, input.clientId),
          eq(clientAdvances.status, 'ativo')
        ));
      const totalBalance = advances.reduce((sum, a) => sum + parseFloat(a.balanceRemaining || '0'), 0);
      return { totalBalance, advances };
    }),

  // Listar deduções de um adiantamento
  listDeductions: protectedProcedure
    .input(z.object({ clientId: z.number() }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      return db.select().from(clientAdvanceDeductions)
        .where(eq(clientAdvanceDeductions.clientId, input.clientId))
        .orderBy(desc(clientAdvanceDeductions.date));
    }),

  // Listar TODAS as deduções (para o controle de cargas sem filtro de cliente)
  listAllDeductions: protectedProcedure
    .query(async () => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      return db.select().from(clientAdvanceDeductions)
        .orderBy(desc(clientAdvanceDeductions.date));
    }),

  // Aplicar abatimento manual em um adiantamento (para fechamento semanal)
  applyDeduction: protectedProcedure
    .input(z.object({
      advanceId: z.number(),
      clientId: z.number(),
      amount: z.number().positive(),
      description: z.string().optional(),
      weeklyClosingId: z.number().optional(),
      cargoLoadId: z.number().optional(),
      date: z.string(),
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });

      // Buscar o adiantamento
      const [advance] = await db.select().from(clientAdvances)
        .where(eq(clientAdvances.id, input.advanceId));
      if (!advance) throw new TRPCError({ code: "NOT_FOUND", message: "Adiantamento não encontrado" });

      const balanceBefore = parseFloat(advance.balanceRemaining || '0');
      if (balanceBefore <= 0) throw new TRPCError({ code: "BAD_REQUEST", message: "Saldo insuficiente" });

      const deductAmount = Math.min(input.amount, balanceBefore);
      const balanceAfter = balanceBefore - deductAmount;

      // Registrar a dedução
      await db.insert(clientAdvanceDeductions).values({
        advanceId: input.advanceId,
        clientId: input.clientId,
        cargoLoadId: input.cargoLoadId,
        weeklyClosingId: input.weeklyClosingId,
        amount: String(deductAmount),
        balanceBefore: String(balanceBefore),
        balanceAfter: String(balanceAfter),
        description: input.description,
        date: input.date,
      });

      // Marcar carga como paga se foi abatida via adiantamento
      if (input.cargoLoadId && deductAmount > 0) {
        try {
          await db.update(cargoLoads)
            .set({ paymentStatus: 'pago', paidAt: new Date().toISOString().slice(0, 19).replace('T', ' ') })
            .where(eq(cargoLoads.id, input.cargoLoadId));
        } catch (e) { console.error('[clientAdvances] Erro ao marcar carga como paga:', e); }
      }

      // Se vinculado a um fechamento semanal, verificar se o fechamento está totalmente coberto
      if (input.weeklyClosingId && deductAmount > 0) {
        try {
          // Buscar o fechamento
          const [closing] = await db.select().from(cargoWeeklyClosings)
            .where(eq(cargoWeeklyClosings.id, input.weeklyClosingId)).limit(1);
          if (closing && closing.status !== 'pago') {
            // Calcular total já deduzido para este fechamento (incluindo a dedução recém criada)
            const deductions = await db.select().from(clientAdvanceDeductions)
              .where(eq(clientAdvanceDeductions.weeklyClosingId, input.weeklyClosingId));
            const totalDeducted = deductions.reduce((sum, d) => sum + parseFloat(d.amount || '0'), 0) + deductAmount;
            const totalAmount = parseFloat(closing.totalAmount || '0');
            if (totalAmount > 0 && totalDeducted >= totalAmount * 0.99) {
              const now = new Date().toISOString().slice(0, 19).replace('T', ' ');
              await db.update(cargoWeeklyClosings)
                .set({ status: 'pago', paidAt: now })
                .where(eq(cargoWeeklyClosings.id, input.weeklyClosingId));
            }
          }
        } catch (e) { console.error('[clientAdvances] Erro ao atualizar fechamento:', e); }
      }

      // Atualizar saldo do adiantamento
      await db.update(clientAdvances)
        .set({
          balanceRemaining: String(balanceAfter),
          status: balanceAfter <= 0 ? 'quitado' : 'ativo',
        })
        .where(eq(clientAdvances.id, input.advanceId));

      return { deductAmount, balanceAfter };
    }),

  // Abatimento automático: aplica o saldo do adiantamento nas cargas entregues em ordem cronológica
  applyAutoDeductionByLoads: protectedProcedure
    .input(z.object({
      clientId: z.number(),
      advanceId: z.number(),
      // Cargas a abater: array de { id, date, valueAmount } ordenadas da mais antiga para a mais nova
      loads: z.array(z.object({
        id: z.number(),
        date: z.string(),
        valueAmount: z.number(), // valor em R$ desta carga
        description: z.string().optional(),
      })),
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });

      // Buscar o adiantamento
      const [advance] = await db.select().from(clientAdvances)
        .where(and(eq(clientAdvances.id, input.advanceId), eq(clientAdvances.clientId, input.clientId)));
      if (!advance) throw new TRPCError({ code: "NOT_FOUND", message: "Adiantamento não encontrado" });

      let balanceRemaining = parseFloat(advance.balanceRemaining || '0');
      if (balanceRemaining <= 0) throw new TRPCError({ code: "BAD_REQUEST", message: "Saldo do adiantamento já esgotado" });

      const results: Array<{
        loadId: number;
        date: string;
        loadValue: number;
        deducted: number;
        balanceBefore: number;
        balanceAfter: number;
        status: 'abatido_total' | 'abatido_parcial' | 'saldo_insuficiente';
      }> = [];

      // Ordenar cargas por data (mais antiga primeiro)
      const sortedLoads = [...input.loads].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

      for (const load of sortedLoads) {
        if (balanceRemaining <= 0) {
          results.push({
            loadId: load.id,
            date: load.date,
            loadValue: load.valueAmount,
            deducted: 0,
            balanceBefore: 0,
            balanceAfter: 0,
            status: 'saldo_insuficiente',
          });
          continue;
        }

        const balanceBefore = balanceRemaining;
        const deducted = Math.min(load.valueAmount, balanceRemaining);
        const balanceAfter = balanceRemaining - deducted;

        // Marcar carga como paga via adiantamento
        try {
          await db.update(cargoLoads)
            .set({ paymentStatus: 'pago', paidAt: new Date().toISOString().slice(0, 19).replace('T', ' ') })
            .where(eq(cargoLoads.id, load.id));
        } catch (e) { console.error('[clientAdvances] Erro ao marcar carga como paga:', e); }
        // Registrar a dedução no banco
        await db.insert(clientAdvanceDeductions).values({
          advanceId: input.advanceId,
          clientId: input.clientId,
          cargoLoadId: load.id,
          amount: String(deducted),
          balanceBefore: String(balanceBefore),
          balanceAfter: String(balanceAfter),
          description: load.description || `Abatimento carga #${load.id} - ${new Date(load.date).toLocaleDateString('pt-BR')}`,
          date: load.date,
        });

        balanceRemaining = balanceAfter;

        results.push({
          loadId: load.id,
          date: load.date,
          loadValue: load.valueAmount,
          deducted,
          balanceBefore,
          balanceAfter,
          status: deducted >= load.valueAmount ? 'abatido_total' : 'abatido_parcial',
        });
      }

      // Atualizar saldo do adiantamento
      await db.update(clientAdvances)
        .set({
          balanceRemaining: String(balanceRemaining),
          status: balanceRemaining <= 0 ? 'quitado' : 'ativo',
        })
        .where(eq(clientAdvances.id, input.advanceId));

      return {
        results,
        finalBalance: balanceRemaining,
        totalDeducted: parseFloat(advance.balanceRemaining || '0') - balanceRemaining,
      };
    }),

  // Upload de comprovante para um adiantamento
  uploadReceipt: protectedProcedure
    .input(z.object({
      advanceId: z.number(),
      fileBase64: z.string(),
      mimeType: z.string().default('image/jpeg'),
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      const buffer = Buffer.from(input.fileBase64, 'base64');
      const ext = input.mimeType.includes('pdf') ? 'pdf' : (input.mimeType.split('/')[1] || 'jpg');
      const key = `client-advances/${input.advanceId}/comprovante-${Date.now()}.${ext}`;
      const { url } = await storagePut(key, buffer, input.mimeType);
      await db.update(clientAdvances)
        .set({ receiptUrl: url })
        .where(eq(clientAdvances.id, input.advanceId));
      return { url };
    }),

  // Atualizar adiantamento (amount, description, date, receiptUrl)
  update: protectedProcedure
    .input(z.object({
      id: z.number(),
      amount: z.number().positive().optional(),
      description: z.string().optional().nullable(),
      date: z.string().optional(),
      receiptUrl: z.string().optional().nullable(),
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });

      const [advance] = await db.select().from(clientAdvances).where(eq(clientAdvances.id, input.id));
      if (!advance) throw new TRPCError({ code: "NOT_FOUND", message: "Adiantamento não encontrado" });

      const updateData: any = {};
      if (input.description !== undefined) updateData.description = input.description;
      if (input.date !== undefined) updateData.date = input.date;
      if (input.receiptUrl !== undefined) updateData.receiptUrl = input.receiptUrl;
      if (input.amount !== undefined) {
        // Recalcular balanceRemaining: novo amount - (amount original - balance atual)
        const originalAmount = parseFloat(advance.amount || '0');
        const currentBalance = parseFloat(advance.balanceRemaining || '0');
        const deducted = originalAmount - currentBalance;
        const newBalance = Math.max(0, input.amount - deducted);
        updateData.amount = String(input.amount);
        updateData.balanceRemaining = String(newBalance);
        updateData.status = newBalance <= 0 ? 'quitado' : 'ativo';
      }

      await db.update(clientAdvances).set(updateData).where(eq(clientAdvances.id, input.id));
      return { success: true };
    }),

  // Deletar adiantamento
  // Se force=true, remove deduções e reverte paymentStatus das cargas abatidas
  delete: protectedProcedure
    .input(z.object({ id: z.number(), force: z.boolean().optional() }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      const deductions = await db.select().from(clientAdvanceDeductions)
        .where(eq(clientAdvanceDeductions.advanceId, input.id));
      if (deductions.length > 0 && !input.force) {
        throw new TRPCError({ code: "BAD_REQUEST", message: `Este adiantamento possui ${deductions.length} abatimento(s). Use a opção 'Forçar exclusão' para remover tudo.` });
      }
      if (deductions.length > 0 && input.force) {
        // Reverter paymentStatus APENAS das cargas que foram pagas EXCLUSIVAMENTE via este adiantamento
        // Cargas pagas manualmente (sem deduções vinculadas a este adiantamento, ou com paymentStatus='pago' por outra razão) NÃO devem ser revertidas
        const loadIds = deductions.map(d => d.cargoLoadId).filter(Boolean) as number[];
        for (const loadId of loadIds) {
          try {
            // Verificar se a carga foi paga manualmente (não via adiantamento)
            // Uma carga paga manualmente terá paymentStatus='pago' mas NÃO terá deduções de OUTROS adiantamentos
            // Buscar TODAS as deduções desta carga (de qualquer adiantamento)
            const allCargoDeductions = await db.select()
              .from(clientAdvanceDeductions)
              .where(eq(clientAdvanceDeductions.cargoLoadId, loadId));

            // Deduções de OUTROS adiantamentos (não o que está sendo excluído)
            const otherDeductions = allCargoDeductions.filter(d => d.advanceId !== input.id);

            // Buscar a carga para verificar o status atual
            const [cargo] = await db.select({ paymentStatus: cargoLoads.paymentStatus })
              .from(cargoLoads)
              .where(eq(cargoLoads.id, loadId));

            // Só reverter se:
            // 1. A carga está marcada como paga
            // 2. NÃO há deduções de outros adiantamentos (o pagamento veio APENAS deste adiantamento)
            // 3. A carga não foi paga manualmente (se tiver paidAt mas sem nenhuma dedução, foi manual)
            if (cargo?.paymentStatus === 'pago' && otherDeductions.length === 0) {
              // Verificar se a carga tem deduções deste adiantamento que cobrem 100% do valor
              // Se a soma das deduções deste adiantamento = totalDeducted e não há outros, reverter
              const thisAdvanceDeductions = allCargoDeductions.filter(d => d.advanceId === input.id);
              const totalThisAdvance = thisAdvanceDeductions.reduce((sum, d) => sum + parseFloat(d.amount || '0'), 0);
              // Só reverter se o adiantamento que está sendo excluído foi responsável pelo pagamento
              if (totalThisAdvance > 0) {
                await db.update(cargoLoads)
                  .set({ paymentStatus: 'sem_boleto', paidAt: null } as any)
                  .where(eq(cargoLoads.id, loadId));
              }
            }
            // Se a carga foi paga manualmente (paymentStatus='pago' sem deduções deste adiantamento marcando como pago)
            // ou se há outros adiantamentos cobrindo, NÃO reverter
          } catch (e) { console.error('[clientAdvances] Erro ao reverter carga:', e); }
        }
        // Excluir deduções
        await db.delete(clientAdvanceDeductions).where(eq(clientAdvanceDeductions.advanceId, input.id));
      }
      await db.delete(clientAdvances).where(eq(clientAdvances.id, input.id));
      return { success: true };
    }),

  // Limpar deduções duplicadas de um adiantamento (manter apenas a mais antiga por cargo_load_id)
  cleanDuplicateDeductions: protectedProcedure
    .input(z.object({ advanceId: z.number() }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'Banco indisponível' });
      // Buscar todas as deduções do adiantamento ordenadas por id (mais antiga primeiro)
      const allDeductions = await db.select()
        .from(clientAdvanceDeductions)
        .where(eq(clientAdvanceDeductions.advanceId, input.advanceId))
        .orderBy(asc(clientAdvanceDeductions.id));
      // Agrupar por cargo_load_id e manter apenas a primeira (mais antiga)
      const seen = new Map();
      const toDelete = [];
      for (const d of allDeductions) {
        const key = d.cargoLoadId;
        if (key === null || key === undefined) continue; // deduções manuais sem carga, manter
        if (!seen.has(key)) {
          seen.set(key, d.id);
        } else {
          toDelete.push(d.id); // duplicata
        }
      }
      for (const id of toDelete) {
        await db.delete(clientAdvanceDeductions).where(eq(clientAdvanceDeductions.id, id));
      }
      // Recalcular saldo do adiantamento com base nas deduções restantes
      const remaining = await db.select()
        .from(clientAdvanceDeductions)
        .where(eq(clientAdvanceDeductions.advanceId, input.advanceId));
      const totalDeducted = remaining.reduce((sum, d) => sum + parseFloat(d.amount || '0'), 0);
      const [advance] = await db.select().from(clientAdvances).where(eq(clientAdvances.id, input.advanceId)).limit(1);
      if (advance) {
        const originalAmount = parseFloat(advance.amount || '0');
        const newBalance = Math.max(0, originalAmount - totalDeducted);
        await db.update(clientAdvances).set({
          balanceRemaining: String(newBalance.toFixed(2)),
          status: newBalance <= 0 ? 'quitado' : 'ativo',
        }).where(eq(clientAdvances.id, input.advanceId));
        return { success: true, deletedCount: toDelete.length, newBalance: newBalance.toFixed(2) };
      }
      return { success: true, deletedCount: toDelete.length, newBalance: null };
    }),

  // Processar abatimentos retroativos: abate automaticamente cargas entregues sem dedução
  processRetroactiveDeductions: protectedProcedure
    .input(z.object({ clientId: z.number() }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'Banco indisponível' });

      // Buscar adiantamentos ativos do cliente
      const advances = await db.select().from(clientAdvances)
        .where(and(eq(clientAdvances.clientId, input.clientId), eq(clientAdvances.status, 'ativo')))
        .orderBy(asc(clientAdvances.date));
      if (advances.length === 0) return { success: true, processed: 0, message: 'Nenhum adiantamento ativo' };

      // Buscar cargas entregues do cliente sem dedução
      const deliveredCargos = await db.select({
        id: cargoLoads.id,
        date: cargoLoads.date,
        weightNetKg: cargoLoads.weightNetKg,
        weightOutKg: cargoLoads.weightOutKg,
        paymentStatus: cargoLoads.paymentStatus,
      }).from(cargoLoads)
        .where(and(
          eq(cargoLoads.clientId, input.clientId),
          eq(cargoLoads.status, 'entregue'),
        ))
        .orderBy(cargoLoads.date);

      // Buscar preço do cliente
      const [client] = await db.select({ pricePerTon: clients.pricePerTon, pricePerM3: clients.pricePerM3 })
        .from(clients).where(eq(clients.id, input.clientId)).limit(1);
      const pricePerTon = parseFloat(client?.pricePerTon || '0');

      let processed = 0;
      const now = new Date().toISOString().slice(0, 19).replace('T', ' ');

      for (const cargo of deliveredCargos) {
        // Verificar se já tem dedução (independente do paymentStatus)
        const existing = await db.select({ id: clientAdvanceDeductions.id })
          .from(clientAdvanceDeductions)
          .where(eq(clientAdvanceDeductions.cargoLoadId, cargo.id))
          .limit(1);
        if (existing.length > 0) continue;

        // Calcular valor da carga
        const weightNet = parseFloat(cargo.weightNetKg || cargo.weightOutKg || '0');
        if (weightNet <= 0 || pricePerTon <= 0) continue;
        const loadValue = (weightNet / 1000) * pricePerTon;
        if (loadValue <= 0) continue;

        const cargoDateStr = typeof cargo.date === 'string' ? cargo.date.slice(0, 10) : new Date(cargo.date).toISOString().slice(0, 10);
        let remainingToDeduct = loadValue;

        for (const advance of advances) {
          if (remainingToDeduct <= 0) break;
          let balanceRemaining = parseFloat(advance.balanceRemaining || '0');
          if (balanceRemaining <= 0) continue;
          const deducted = Math.min(remainingToDeduct, balanceRemaining);
          const balanceBefore = balanceRemaining;
          const balanceAfter = balanceRemaining - deducted;
          await db.insert(clientAdvanceDeductions).values({
            advanceId: advance.id,
            clientId: input.clientId,
            cargoLoadId: cargo.id,
            amount: String(deducted.toFixed(2)),
            balanceBefore: String(balanceBefore.toFixed(2)),
            balanceAfter: String(balanceAfter.toFixed(2)),
            description: `Abatimento retroativo carga #${cargo.id} - ${cargoDateStr}`,
            date: cargoDateStr,
          });
          await db.update(clientAdvances).set({
            balanceRemaining: String(balanceAfter.toFixed(2)),
            status: balanceAfter <= 0 ? 'quitado' : 'ativo',
          }).where(eq(clientAdvances.id, advance.id));
          advance.balanceRemaining = String(balanceAfter.toFixed(2));
          remainingToDeduct -= deducted;
        }
        if (remainingToDeduct <= 0.01) {
          await db.update(cargoLoads)
            .set({ paymentStatus: 'pago', paidAt: now })
            .where(eq(cargoLoads.id, cargo.id));
        }
        processed++;
      }
      return { success: true, processed };
    }),
});
