import { z } from "zod";
import { protectedProcedure, router } from "../_core/trpc";
import { TRPCError } from "@trpc/server";
import { getDb } from "../db";
import { clientAdvances, clientAdvanceDeductions, clients, financialEntries, cargoLoads } from "../../drizzle/schema";
import { eq, desc, and, asc } from "drizzle-orm";
import { storagePut } from "../storage";

export const clientAdvancesRouter = router({
  // Listar adiantamentos de um cliente
  list: protectedProcedure
    .input(z.object({ clientId: z.number() }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      return db.select().from(clientAdvances)
        .where(eq(clientAdvances.clientId, input.clientId))
        .orderBy(desc(clientAdvances.date));
    }),

  // Criar novo adiantamento
  create: protectedProcedure
    .input(z.object({
      clientId: z.number(),
      amount: z.number().positive(),
      description: z.string().optional(),
      receiptUrl: z.string().optional(),
      date: z.string(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      // Buscar nome do cliente
      const [client] = await db.select({ name: clients.name }).from(clients).where(eq(clients.id, input.clientId));
      const clientName = client?.name || `Cliente #${input.clientId}`;

      const [result] = await db.insert(clientAdvances).values({
        clientId: input.clientId,
        amount: String(input.amount),
        balanceRemaining: String(input.amount),
        description: input.description,
        receiptUrl: input.receiptUrl,
        date: input.date,
        status: 'ativo',
        createdBy: ctx.user.id,
      });
      const advanceId = (result as any).insertId;

      // Lançar automaticamente no financeiro como despesa
      try {
        const refMonth = input.date.slice(0, 7); // "2026-05"
        const desc = input.description
          ? `Adiantamento para ${clientName} - ${input.description}`
          : `Adiantamento para ${clientName}`;
        await db.insert(financialEntries).values({
          type: 'despesa',
          category: 'adiantamento_cliente',
          description: desc,
          amount: String(input.amount),
          date: input.date,
          referenceMonth: refMonth,
          paymentMethod: 'pix',
          status: 'confirmado',
          clientId: input.clientId,
          clientName,
          notes: `Adiantamento ID #${advanceId} registrado automaticamente`,
          registeredBy: ctx.user.id,
          registeredByName: ctx.user.name,
          autoGenerated: 1,
        });
      } catch (e) {
        // Não bloquear criação do adiantamento se o lançamento financeiro falhar
        console.error('[clientAdvances] Erro ao lançar no financeiro:', e);
      }

      return { id: advanceId };
    }),

  // Buscar saldo total de adiantamentos ativos de um cliente
  getBalance: protectedProcedure
    .input(z.object({ clientId: z.number() }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      const advances = await db.select().from(clientAdvances)
        .where(and(
          eq(clientAdvances.clientId, input.clientId),
          eq(clientAdvances.status, 'ativo')
        ));
      const totalBalance = advances.reduce((sum, a) => sum + parseFloat(a.balanceRemaining || '0'), 0);
      return { totalBalance, advances };
    }),

  // Listar deduções de um adiantamento
  listDeductions: protectedProcedure
    .input(z.object({ clientId: z.number() }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      return db.select().from(clientAdvanceDeductions)
        .where(eq(clientAdvanceDeductions.clientId, input.clientId))
        .orderBy(desc(clientAdvanceDeductions.date));
    }),

  // Aplicar abatimento manual em um adiantamento (para fechamento semanal)
  applyDeduction: protectedProcedure
    .input(z.object({
      advanceId: z.number(),
      clientId: z.number(),
      amount: z.number().positive(),
      description: z.string().optional(),
      weeklyClosingId: z.number().optional(),
      cargoLoadId: z.number().optional(),
      date: z.string(),
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });

      // Buscar o adiantamento
      const [advance] = await db.select().from(clientAdvances)
        .where(eq(clientAdvances.id, input.advanceId));
      if (!advance) throw new TRPCError({ code: "NOT_FOUND", message: "Adiantamento não encontrado" });

      const balanceBefore = parseFloat(advance.balanceRemaining || '0');
      if (balanceBefore <= 0) throw new TRPCError({ code: "BAD_REQUEST", message: "Saldo insuficiente" });

      const deductAmount = Math.min(input.amount, balanceBefore);
      const balanceAfter = balanceBefore - deductAmount;

      // Registrar a dedução
      await db.insert(clientAdvanceDeductions).values({
        advanceId: input.advanceId,
        clientId: input.clientId,
        cargoLoadId: input.cargoLoadId,
        weeklyClosingId: input.weeklyClosingId,
        amount: String(deductAmount),
        balanceBefore: String(balanceBefore),
        balanceAfter: String(balanceAfter),
        description: input.description,
        date: input.date,
      });

      // Marcar carga como paga se foi abatida via adiantamento
      if (input.cargoLoadId && deductAmount > 0) {
        try {
          await db.update(cargoLoads)
            .set({ paymentStatus: 'pago', paidAt: new Date().toISOString().slice(0, 19).replace('T', ' ') })
            .where(eq(cargoLoads.id, input.cargoLoadId));
        } catch (e) { console.error('[clientAdvances] Erro ao marcar carga como paga:', e); }
      }
      // Atualizar saldo do adiantamento
      await db.update(clientAdvances)
        .set({
          balanceRemaining: String(balanceAfter),
          status: balanceAfter <= 0 ? 'quitado' : 'ativo',
        })
        .where(eq(clientAdvances.id, input.advanceId));

      return { deductAmount, balanceAfter };
    }),

  // Abatimento automático: aplica o saldo do adiantamento nas cargas entregues em ordem cronológica
  applyAutoDeductionByLoads: protectedProcedure
    .input(z.object({
      clientId: z.number(),
      advanceId: z.number(),
      // Cargas a abater: array de { id, date, valueAmount } ordenadas da mais antiga para a mais nova
      loads: z.array(z.object({
        id: z.number(),
        date: z.string(),
        valueAmount: z.number(), // valor em R$ desta carga
        description: z.string().optional(),
      })),
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });

      // Buscar o adiantamento
      const [advance] = await db.select().from(clientAdvances)
        .where(and(eq(clientAdvances.id, input.advanceId), eq(clientAdvances.clientId, input.clientId)));
      if (!advance) throw new TRPCError({ code: "NOT_FOUND", message: "Adiantamento não encontrado" });

      let balanceRemaining = parseFloat(advance.balanceRemaining || '0');
      if (balanceRemaining <= 0) throw new TRPCError({ code: "BAD_REQUEST", message: "Saldo do adiantamento já esgotado" });

      const results: Array<{
        loadId: number;
        date: string;
        loadValue: number;
        deducted: number;
        balanceBefore: number;
        balanceAfter: number;
        status: 'abatido_total' | 'abatido_parcial' | 'saldo_insuficiente';
      }> = [];

      // Ordenar cargas por data (mais antiga primeiro)
      const sortedLoads = [...input.loads].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

      for (const load of sortedLoads) {
        if (balanceRemaining <= 0) {
          results.push({
            loadId: load.id,
            date: load.date,
            loadValue: load.valueAmount,
            deducted: 0,
            balanceBefore: 0,
            balanceAfter: 0,
            status: 'saldo_insuficiente',
          });
          continue;
        }

        const balanceBefore = balanceRemaining;
        const deducted = Math.min(load.valueAmount, balanceRemaining);
        const balanceAfter = balanceRemaining - deducted;

        // Marcar carga como paga via adiantamento
        try {
          await db.update(cargoLoads)
            .set({ paymentStatus: 'pago', paidAt: new Date().toISOString().slice(0, 19).replace('T', ' ') })
            .where(eq(cargoLoads.id, load.id));
        } catch (e) { console.error('[clientAdvances] Erro ao marcar carga como paga:', e); }
        // Registrar a dedução no banco
        await db.insert(clientAdvanceDeductions).values({
          advanceId: input.advanceId,
          clientId: input.clientId,
          cargoLoadId: load.id,
          amount: String(deducted),
          balanceBefore: String(balanceBefore),
          balanceAfter: String(balanceAfter),
          description: load.description || `Abatimento carga #${load.id} - ${new Date(load.date).toLocaleDateString('pt-BR')}`,
          date: load.date,
        });

        balanceRemaining = balanceAfter;

        results.push({
          loadId: load.id,
          date: load.date,
          loadValue: load.valueAmount,
          deducted,
          balanceBefore,
          balanceAfter,
          status: deducted >= load.valueAmount ? 'abatido_total' : 'abatido_parcial',
        });
      }

      // Atualizar saldo do adiantamento
      await db.update(clientAdvances)
        .set({
          balanceRemaining: String(balanceRemaining),
          status: balanceRemaining <= 0 ? 'quitado' : 'ativo',
        })
        .where(eq(clientAdvances.id, input.advanceId));

      return {
        results,
        finalBalance: balanceRemaining,
        totalDeducted: parseFloat(advance.balanceRemaining || '0') - balanceRemaining,
      };
    }),

  // Upload de comprovante para um adiantamento
  uploadReceipt: protectedProcedure
    .input(z.object({
      advanceId: z.number(),
      fileBase64: z.string(),
      mimeType: z.string().default('image/jpeg'),
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      const buffer = Buffer.from(input.fileBase64, 'base64');
      const ext = input.mimeType.includes('pdf') ? 'pdf' : (input.mimeType.split('/')[1] || 'jpg');
      const key = `client-advances/${input.advanceId}/comprovante-${Date.now()}.${ext}`;
      const { url } = await storagePut(key, buffer, input.mimeType);
      await db.update(clientAdvances)
        .set({ receiptUrl: url })
        .where(eq(clientAdvances.id, input.advanceId));
      return { url };
    }),

  // Atualizar adiantamento (amount, description, date, receiptUrl)
  update: protectedProcedure
    .input(z.object({
      id: z.number(),
      amount: z.number().positive().optional(),
      description: z.string().optional().nullable(),
      date: z.string().optional(),
      receiptUrl: z.string().optional().nullable(),
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });

      const [advance] = await db.select().from(clientAdvances).where(eq(clientAdvances.id, input.id));
      if (!advance) throw new TRPCError({ code: "NOT_FOUND", message: "Adiantamento não encontrado" });

      const updateData: any = {};
      if (input.description !== undefined) updateData.description = input.description;
      if (input.date !== undefined) updateData.date = input.date;
      if (input.receiptUrl !== undefined) updateData.receiptUrl = input.receiptUrl;
      if (input.amount !== undefined) {
        // Recalcular balanceRemaining: novo amount - (amount original - balance atual)
        const originalAmount = parseFloat(advance.amount || '0');
        const currentBalance = parseFloat(advance.balanceRemaining || '0');
        const deducted = originalAmount - currentBalance;
        const newBalance = Math.max(0, input.amount - deducted);
        updateData.amount = String(input.amount);
        updateData.balanceRemaining = String(newBalance);
        updateData.status = newBalance <= 0 ? 'quitado' : 'ativo';
      }

      await db.update(clientAdvances).set(updateData).where(eq(clientAdvances.id, input.id));
      return { success: true };
    }),

  // Deletar adiantamento
  // Se force=true, remove deduções e reverte paymentStatus das cargas abatidas
  delete: protectedProcedure
    .input(z.object({ id: z.number(), force: z.boolean().optional() }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível" });
      const deductions = await db.select().from(clientAdvanceDeductions)
        .where(eq(clientAdvanceDeductions.advanceId, input.id));
      if (deductions.length > 0 && !input.force) {
        throw new TRPCError({ code: "BAD_REQUEST", message: `Este adiantamento possui ${deductions.length} abatimento(s). Use a opção 'Forçar exclusão' para remover tudo.` });
      }
      if (deductions.length > 0 && input.force) {
        // Reverter paymentStatus das cargas abatidas
        const loadIds = deductions.map(d => d.cargoLoadId).filter(Boolean) as number[];
        for (const loadId of loadIds) {
          try {
            await db.update(cargoLoads)
              .set({ paymentStatus: 'sem_boleto', paidAt: null })
              .where(eq(cargoLoads.id, loadId));
          } catch (e) { console.error('[clientAdvances] Erro ao reverter carga:', e); }
        }
        // Excluir deduções
        await db.delete(clientAdvanceDeductions).where(eq(clientAdvanceDeductions.advanceId, input.id));
      }
      await db.delete(clientAdvances).where(eq(clientAdvances.id, input.id));
      return { success: true };
    }),
});
