/**
 * Auto-Financial: Gera lançamentos financeiros automáticos quando uma carga é entregue.
 * 
 * - RECEITA: preço do comprador (destino) × peso líquido em toneladas
 * - DESPESA: preço do cliente (fornecedor da madeira) × peso líquido em toneladas
 */
import { getDb } from './db';
import { financialEntries, clients, buyerClients, cargoLoads } from '../drizzle/schema';
import { eq } from 'drizzle-orm';

interface CargoData {
  id: number;
  clientId?: number | null;
  clientName?: string | null;
  destinationId?: number | null;
  destination?: string | null;
  weightNetKg?: string | null;
  date: string;
  invoiceNumber?: string | null;
  vehiclePlate?: string | null;
}

export async function generateFinancialEntriesForCargo(cargo: CargoData, userId: number, userName: string) {
  const db = await getDb();
  if (!db) return;

  const weightNetKg = parseFloat(cargo.weightNetKg || '0');
  if (weightNetKg <= 0) return; // Sem peso líquido, não gera lançamento

  const weightTon = weightNetKg / 1000;
  const dateObj = new Date(cargo.date);
  const refMonth = `${dateObj.getFullYear()}-${String(dateObj.getMonth() + 1).padStart(2, '0')}`;
  const dateFmt = dateObj.toLocaleDateString('pt-BR');

  // Check if auto-generated entries already exist for this cargo
  const existing = await db.select().from(financialEntries)
    .where(eq(financialEntries.cargoLoadId, cargo.id));
  
  if (existing.length > 0) return; // Already generated

  // ── RECEITA: Preço do comprador (destino) ──
  if (cargo.destinationId) {
    const [buyer] = await db.select().from(buyerClients).where(eq(buyerClients.id, cargo.destinationId)).limit(1);
    if (buyer && buyer.pricePerUnit) {
      const pricePerTon = parseFloat(buyer.pricePerUnit);
      if (pricePerTon > 0) {
        const revenueAmount = (weightTon * pricePerTon).toFixed(2);
        await db.insert(financialEntries).values({
          type: 'receita',
          category: 'Venda de Madeira',
          description: `Carga #${cargo.id} - ${buyer.name} - ${weightTon.toFixed(3)} ton × R$ ${pricePerTon.toFixed(2)}/ton - NF: ${cargo.invoiceNumber || 'S/N'} - Placa: ${cargo.vehiclePlate || 'N/I'}`,
          amount: revenueAmount,
          date: dateObj.toISOString().slice(0, 19).replace('T', ' '),
          referenceMonth: refMonth,
          paymentMethod: 'transferencia',
          status: 'pendente',
          clientId: cargo.destinationId,
          clientName: buyer.name,
          cargoLoadId: cargo.id,
          autoGenerated: 1,
          registeredBy: userId,
          registeredByName: userName + ' (auto)',
        });
      }
    }
  }

  // ── DESPESA: Preço do cliente (fornecedor da madeira) ──
  if (cargo.clientId) {
    const [client] = await db.select().from(clients).where(eq(clients.id, cargo.clientId)).limit(1);
    if (client && client.pricePerTon) {
      const pricePerTon = parseFloat(client.pricePerTon);
      if (pricePerTon > 0) {
        const expenseAmount = (weightTon * pricePerTon).toFixed(2);
        await db.insert(financialEntries).values({
          type: 'despesa',
          category: 'Pagamento Fornecedor Madeira',
          description: `Carga #${cargo.id} - ${client.name} - ${weightTon.toFixed(3)} ton × R$ ${pricePerTon.toFixed(2)}/ton - NF: ${cargo.invoiceNumber || 'S/N'} - Placa: ${cargo.vehiclePlate || 'N/I'}`,
          amount: expenseAmount,
          date: dateObj.toISOString().slice(0, 19).replace('T', ' '),
          referenceMonth: refMonth,
          paymentMethod: 'transferencia',
          status: 'pendente',
          clientId: cargo.clientId,
          clientName: client.name,
          cargoLoadId: cargo.id,
          autoGenerated: 1,
          registeredBy: userId,
          registeredByName: userName + ' (auto)',
        });
      }
    }
  }
}
