/** Lançamentos de cargas entregues; área pendente nunca herda o custo do cliente. */
import { getDb } from './db';
import { financialEntries, clients, cargoDestinations } from '../drizzle/schema';
import { eq } from 'drizzle-orm';
import { getClientArea, getCargoFinancialValue, getAreaPriceTerms, normalizeAreaId, financialNumber } from './lib/clientAreaScope';

interface CargoData {
  id: number; clientId?: number | null; clientName?: string | null; areaId?: number | null;
  destinationId?: number | null; destination?: string | null;
  weightNetKg?: string | null; weightOutKg?: string | null;
  volumeM3?: string | null; finalVolumeM3?: string | null;
  agreedUnit?: string | null; agreedUnitPrice?: string | null; agreedPaymentMethod?: string | null;
  date: string; invoiceNumber?: string | null; vehiclePlate?: string | null;
}
export async function generateFinancialEntriesForCargo(cargo: CargoData, userId: number, userName: string) {
  const db = await getDb(); if (!db) return;
  const areaId = normalizeAreaId(cargo.areaId);
  const weightTon = financialNumber(cargo.weightNetKg || cargo.weightOutKg) / 1000;
  const volume = financialNumber(cargo.finalVolumeM3 || cargo.volumeM3);
  if (areaId === null ? weightTon <= 0 : weightTon <= 0 && volume <= 0) return;
  const dateObj = new Date(cargo.date);
  const common = {areaId, date: dateObj.toISOString().slice(0,19).replace('T',' '), referenceMonth: `${dateObj.getFullYear()}-${String(dateObj.getMonth()+1).padStart(2,'0')}`, cargoLoadId:cargo.id, autoGenerated:1, registeredBy:userId, registeredByName:userName+' (auto)'};
  const existing = await db.select().from(financialEntries).where(eq(financialEntries.cargoLoadId,cargo.id));
  // Preservar a prevenção de duplicatas histórica; em novas áreas uma receita
  // anterior não impede que a despesa seja criada após confirmar o acordo.
  if (areaId === null && existing.length) return;
  if (cargo.destinationId && !existing.some((e:any)=>e.type==='receita')) {
    const destinationId = cargo.destinationId >= 10000 ? cargo.destinationId-10000 : cargo.destinationId;
    const [dest] = await db.select().from(cargoDestinations).where(eq(cargoDestinations.id,destinationId)).limit(1);
    if (dest) {
      const unit = dest.isBuyer ? dest.unit : dest.priceType;
      const price = financialNumber(dest.pricePerUnit ?? (unit==='m3'?dest.pricePerM3:dest.pricePerTon));
      const qty = unit==='m3'?volume:weightTon;
      if (price>0 && qty>0) await db.insert(financialEntries).values({...common,type:'receita',category:'venda_madeira',description:`Carga #${cargo.id} - ${dest.name} - ${qty.toFixed(3)} ${unit==='m3'?'m³':'ton'} × R$ ${price.toFixed(2)} - NF: ${cargo.invoiceNumber||'S/N'}`,amount:(qty*price).toFixed(2),paymentMethod:'transferencia',status:'pendente',clientName:dest.name});
    }
  }
  if (cargo.clientId && !existing.some((e:any)=>e.type==='despesa' && e.category==='Pagamento Fornecedor Madeira')) {
    const [client]=await db.select().from(clients).where(eq(clients.id,cargo.clientId)).limit(1);
    if (!client) return;
    const area=await getClientArea(db,cargo.clientId,areaId);
    const terms=getAreaPriceTerms(client,area);
    if (!terms) return;
    const value=getCargoFinancialValue(cargo,client,area);
    if (value==null || value<=0) return;
    const areaLabel=area?` — ${area.fieldName?area.fieldName+' — ':''}${area.name}`:'';
    await db.insert(financialEntries).values({...common,type:'despesa',category:'Pagamento Fornecedor Madeira',description:`Carga #${cargo.id} - ${client.name}${areaLabel} - NF: ${cargo.invoiceNumber||'S/N'} - Placa: ${cargo.vehiclePlate||'N/I'}`,amount:value.toFixed(2),paymentMethod:area?(cargo.agreedPaymentMethod||terms.paymentMethod||'transferencia'):'transferencia',status:'pendente',clientId:cargo.clientId,clientName:client.name});
  }
}
